ALTER TABLE "Booking"
ADD COLUMN "accountAmount" DECIMAL(12,2),
ADD COLUMN "cashAmount" DECIMAL(12,2),
ADD COLUMN "cardAmount" DECIMAL(12,2);

ALTER TABLE "CompanyDailyMetric"
ADD COLUMN "cashRevenue" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN "accountRevenue" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN "cardRevenue" DECIMAL(14,2) NOT NULL DEFAULT 0;
