export type AutocabVehicleRecord = {
  id: number;
  rowVersion?: number | null;
  companyId?: number | null;
  callsign?: string | null;
  make?: string | null;
  model?: string | null;
  colour?: string | null;
  yearOfManufacture?: number | null;
  registration?: string | null;
  vehicleType?: string | null;
  capabilities?: unknown;
  size?: number | null;
  isSuspended?: boolean;
  plateNumber?: string | null;
  phoneNumber?: string | null;
  ownerDriverId?: number | null;
  secondOwnerDriverId?: number | null;
  plateExpiryDate?: string | null;
  insuranceExpiryDate?: string | null;
  motExpiryDate?: string | null;
  roadTaxExpiryDate?: string | null;
  mileage?: number | null;
  mdtId?: number | null;
  terminalId?: number | null;
  terminalType?: string | null;
  mdtVersion?: string | null;
  imei?: string | null;
  serial?: string | null;
  simNumber1?: string | null;
  simNumber2?: string | null;
  isActive?: boolean;
  drivers?: unknown;
  fleetOwnerId?: number | null;
  [key: string]: unknown;
};

export type VehicleSyncResult = {
  jobId: string;
  status: "SUCCESS" | "PARTIAL" | "FAILED";
  startedAt: Date;
  finishedAt: Date;
  durationMs: number;
  recordsReceived: number;
  recordsEligible: number;
  recordsCreated: number;
  recordsUpdated: number;
  recordsSkipped: number;
  recordsDisabled: number;
  recordsFailed: number;
  nextSyncAt: Date;
  message: string;
};
